language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21


before_script:

  # First assemble the project before launching the emulator
  # - cd WearHackathon
  # - ./gradlew assemble

  # Emulator Management: Create, Start and Wait
  # the emulator is currently not needed
  # - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

script:
  # build all variants, mobile and wear
  - cd WearHackathon
  - ./gradlew assemble